### ISSUE TITLE
Building for ESP8266 RTOS SDK

### ISSUE THREAD

**Issue by readysteadygo2006** [Lobaro/lobaro-coap-on-esp8266#2]
Hi,

I was wondering if you had made any attempt to build for the ESP8266 RTOS SDK?

I'm currently trying to do this and would appreciate any help!

BR

**Comment by tothero** [comment]
We will release an updated version for FreeRTOS SDK soon!

**Comment by readysteadygo2006** [comment]
Hi,

I've make changes which make Lobaro run under FreeRTOS. I can push them if
you like
there not pretty!

One point, currently you use espconn library for networking, have you
thought about
using the lwip library for the upcoming release as this will make things
much more portable?

BR
Paul
